### ISSUE TITLE
Can't make an account on the app.

### ISSUE THREAD

**Issue by sgrpanchal31** [openfoodfacts/openfoodfacts-ios#51] opened 2018-02-21 12:21 UTC
When we try to create an account throught "create an account" hyperlink in Sign-in Section, it redirects to the openfoodfacts.org's homepage.

**Comment by teolemon** [comment] 2018-02-21 13:28
The url should be https://world.openfoodfacts.org/cgi/user.pl

**Comment by snuff4** [comment] 2018-02-27 19:35
Hi @teolemon, I used both the apps on a physical device, and observed that the issue is in the app currently on the App Store, NOT with the  Swift application.

So we can close this issue.

**Comment by teolemon** [comment] 2018-03-07 13:51
thanks @snuff4

**Closed** 2018-03-07 13:51 UTC
Labels: account-management
